import asyncio
import sys
import os
from config import SYSTEM_NAME
from database.db_manager import SilentMemoryManager
from background.task_queue import SilentBackgroundEngine
from router.model_selector.py import SilentRouter # Adjust import based on execution directory

# Mock OS action function to demonstrate background worker threading
def mock_file_automation_task(task_details):
    import time
        # Simulating long system operations like scanning directories or building files
            time.sleep(5) 
                print(f"\n\n[Silent Task Engine]: Background task execution complete for: '{task_details}'")

                async def interactive_terminal():
                    # Instantiate core structural layers
                        db = SilentMemoryManager()
                            bg_engine = SilentBackgroundEngine()
                                router = SilentRouter()

                                    # Spin up the background worker queue loop silently
                                        asyncio.create_task(bg_engine.start_loop())

                                            # Change this variable to shift dialects dynamically ("Haryanvi", "Gujarati", "Hinglish")
                                                current_dialect = "Haryanvi" 

                                                    print(f"=== {SYSTEM_NAME.upper()} CORE INITIALIZED ===")
                                                        print(f"Current Dialect Configuration: {current_dialect}")
                                                            print("Type 'exit' to quit. Type 'backup <path>' to export your database snapshot to a pendrive.\n")

                                                                while True:
                                                                        try:
                                                                                    # Read input from the terminal lines
                                                                                                user_input = input(f"You ({current_dialect}): ").strip()
                                                                                                            if not user_input:
                                                                                                                            continue
                                                                                                                                            
                                                                                                                                                        if user_input.lower() == 'exit':
                                                                                                                                                                        print(f"Shutting down {SYSTEM_NAME}. Real-time logs safely written to SQLite database.")
                                                                                                                                                                                        break

                                                                                                                                                                                                    # Handle portable backup commands
                                                                                                                                                                                                                if user_input.lower().startswith("backup"):
                                                                                                                                                                                                                                _, target_path = user_input.split(" ", 1)
                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                    result = db.export_memory_snapshot(target_path)
                                                                                                                                                                                                                                                                                        print(f"[{SYSTEM_NAME}]: {result}")
                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                            print(f"Backup failed: {str(e)}")
                                                                                                                                                                                                                                                                                                                                            continue

                                                                                                                                                                                                                                                                                                                                                        # Step 1: Route task through the classification layer
                                                                                                                                                                                                                                                                                                                                                                    task_category = router.analyze_and_route_task(user_input)

                                                                                                                                                                                                                                                                                                                                                                                # Step 2: Handle Background Execution vs Direct Conversational Chat
                                                                                                                                                                                                                                                                                                                                                                                            if task_category in ["OS_AUTOMATION", "CODING"]:
                                                                                                                                                                                                                                                                                                                                                                                                            print(f"\n[{SYSTEM_NAME}]: I recognized this as a {task_category} task. Moving to background processing queue...")
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                            # Dispatch to asyncio worker queue without blocking terminal execution lines
                                                                                                                                                                                                                                                                                                                                                                                                                                                            await bg_engine.dispatch_task(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description=user_input,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sync_function=mock_file_automation_task,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        task_details=user_input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Fetch polite regional acknowledgement
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reply = router.get_regional_response(f"Acknowledge that you have put this task into the background queue: {user_input}", dialect=current_dialect)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"{SYSTEM_NAME}: {reply}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Permanently write transactions to transaction ledger
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.log_conversation(user_input, reply, current_dialect, "System_Queue_Dispatcher")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Handle standard conversational tasks in real time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reply = router.get_regional_response(user_input, dialect=current_dialect)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"{SYSTEM_NAME}: {reply}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Log interaction safely to database
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.log_conversation(user_input, reply, current_dialect, "llama3.3:8b")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except (KeyboardInterrupt, EOFError):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nExiting cleanly...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Ensure asyncio terminal loop handles cleanly across operating systems
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if sys.platform == 'win32':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        asyncio.run(interactive_terminal())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        