import requests
import json
from config import OLLAMA_API_URL, GENERAL_MODEL, ROUTER_MODEL

class SilentRouter:
    def __init__(self):
            self.api_url = f"{OLLAMA_API_URL}/chat"

                def get_regional_response(self, user_message, dialect="Haryanvi"):
                        """
                                Injects a behavior context layer instructing the local model 
                                        to speak naturally in the user's preferred regional language.
                                                """
                                                        
                                                                # System instructions configured specifically for accessibility 
                                                                        system_prompt = (
                                                                                    f"You are an AI assistant named Silent. You are friendly, user-friendly, and helping your brother. "
                                                                                                f"You MUST completely understand and reply strictly in the following regional Indian dialect/language: '{dialect}'. "
                                                                                                            f"Do not use highly formal textbook words. Talk like a local peer or friend would naturally speak. "
                                                                                                                        f"If the user asks you to do a task, acknowledge it warmly in '{dialect}' and say it is being handled."
                                                                                                                                )

                                                                                                                                        payload = {
                                                                                                                                                    "model": GENERAL_MODEL,
                                                                                                                                                                "messages": [
                                                                                                                                                                                {"role": "system", "content": system_prompt},
                                                                                                                                                                                                {"role": "user", "content": user_message}
                                                                                                                                                                                                            ],
                                                                                                                                                                                                                        "stream": False # Set to False for cleaner execution parsing inside custom logs
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                    response = requests.post(self.api_url, json=payload, timeout=30)
                                                                                                                                                                                                                                                                if response.status_code == 200:
                                                                                                                                                                                                                                                                                # Parse standard JSON response from Ollama endpoint
                                                                                                                                                                                                                                                                                                response_data = response.json()
                                                                                                                                                                                                                                                                                                                return response_data['message']['content']
                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                            return f"Bhai, Ollama backend error code dikha rya h: {response.status_code}"
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                    except requests.exceptions.ConnectionError:
                                                                                                                                                                                                                                                                                                                                                                                return "Error: Ollama application isn't running! Please start Ollama on your laptop first."
                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                    return f"An unhandled error occurred: {str(e)}"

                                                                                                                                                                                                                                                                                                                                                                                                        def analyze_and_route_task(self, user_command):
                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                        Decision Matrix: A lightweight model acts as the router to decide 
                                                                                                                                                                                                                                                                                                                                                                                                                                if a task is a deep coding task, file manipulation, or standard talk.
                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                router_prompt = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Analyze this user command. Classify it into exactly one of these categories: "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "['GENERAL', 'OS_AUTOMATION', 'CODING']. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Respond with ONLY the category name in plain text, nothing else. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"Command: {user_command}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        payload = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "model": ROUTER_MODEL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "messages": [{"role": "user", "content": router_prompt}],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "stream": False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res = requests.post(self.api_url, json=payload, timeout=10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if res.status_code == 200:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            classification = res.json()['message']['content'].strip().upper()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Clean up dirty model outputs if any extra text sneaks in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for category in ['OS_AUTOMATION', 'CODING']:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if category in classification:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return category
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return "GENERAL"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return "GENERAL" # Safe fallback
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        