import sqlite3
import os
from datetime import datetime
from pathlib import Path
from config import DB_DIR

class SilentMemoryManager:
    def __init__(self):
            self.db_path = DB_DIR / "silent_memory.db"
                    self._initialize_database()

                        def _get_connection(self):
                                """Creates a connection and strictly enforces WAL mode for fault tolerance."""
                                        conn = sqlite3.connect(self.db_path)
                                                # WAL mode ensures logs are written sequentially; protects against power cut corruption
                                                        conn.execute("PRAGMA journal_mode=WAL;")
                                                                conn.execute("PRAGMA synchronous=NORMAL;")
                                                                        return conn

                                                                            def _initialize_database(self):
                                                                                    """Creates tables for conversation tracking and background operations if absent."""
                                                                                            query_history = """
                                                                                                    CREATE TABLE IF NOT EXISTS conversation_history (
                                                                                                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                                                            timestamp TEXT NOT NULL,
                                                                                                                                        user_input TEXT NOT NULL,
                                                                                                                                                    system_response TEXT NOT NULL,
                                                                                                                                                                language_used TEXT NOT NULL,
                                                                                                                                                                            chosen_model TEXT NOT NULL
                                                                                                                                                                                    );
                                                                                                                                                                                            """
                                                                                                                                                                                                    query_tasks = """
                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS task_registry (
                                                                                                                                                                                                                        task_id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                    timestamp TEXT NOT NULL,
                                                                                                                                                                                                                                                task_description TEXT NOT NULL,
                                                                                                                                                                                                                                                            status TEXT CHECK(status IN ('pending', 'running', 'completed', 'failed')) NOT NULL,
                                                                                                                                                                                                                                                                        assigned_model TEXT NOT NULL,
                                                                                                                                                                                                                                                                                    error_log TEXT
                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    with self._get_connection() as conn:
                                                                                                                                                                                                                                                                                                                                conn.execute(query_history)
                                                                                                                                                                                                                                                                                                                                            conn.execute(query_tasks)
                                                                                                                                                                                                                                                                                                                                                        conn.commit()

                                                                                                                                                                                                                                                                                                                                                            def log_conversation(self, user_input, response, language, model):
                                                                                                                                                                                                                                                                                                                                                                    """Permanently records dialogue history."""
                                                                                                                                                                                                                                                                                                                                                                            query = """
                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO conversation_history (timestamp, user_input, system_response, language_used, chosen_model)
                                                                                                                                                                                                                                                                                                                                                                                            VALUES (?, ?, ?, ?, ?);
                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                            timestamp = datetime.now().isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                    with self._get_connection() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                conn.execute(query, (timestamp, user_input, response, language, model))
                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                def register_task(self, task_id, description, model):
                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Logs a brand new background task inside the queue framework."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                query = """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO task_registry (task_id, timestamp, task_description, status, assigned_model, error_log)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (?, ?, ?, 'pending', ?, NULL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp = datetime.now().isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with self._get_connection() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.execute(query, (task_id, timestamp, description, model))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def update_task_status(self, task_id, status, error_log=None):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Updates background task status and logs errors if things go sideways."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    query = "UPDATE task_registry SET status = ?, error_log = ? WHERE task_id = ?;"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with self._get_connection() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.execute(query, (status, error_log, task_id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.commit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def export_memory_snapshot(self, target_pendrive_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Safely flushes active WAL logs and bakes database down into a clean, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                single file copy onto a flash drive without risking corruption.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backup_file = Path(target_pendrive_path) / "backup_silent_memory.db"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with self._get_connection() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Forces SQLite to merge WAL logs back into main file database before copying
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.execute("PRAGMA wal_checkpoint(TRUNCATE);")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Atomic backup command safe against system active locks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backup_conn = sqlite3.connect(backup_file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with backup_conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.backup(backup_conn)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backup_conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return f"Memory successfully mirrored to pendrive at: {backup_file}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        