import asyncio
import uuid
import traceback
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor
from database.db_manager import SilentMemoryManager

class SilentBackgroundEngine:
    def __init__(self):
            self.db = SilentMemoryManager()
                    # Allows execution of non-async OS blocking scripts smoothly in isolated threads
                            self.thread_executor = ThreadPoolExecutor(max_workers=3)
                                    self.queue = asyncio.Queue()
                                            
                                                async def start_loop(self):
                                                        """Keeps the background daemon running forever to catch incoming user tasks."""
                                                                while True:
                                                                            task_data = await self.queue.get()
                                                                                        asyncio.create_task(self._execute_worker(task_data))
                                                                                                    self.queue.task_done()

                                                                                                        async def dispatch_task(self, description, sync_function, *args, assigned_model="qwen2.5-coder:7b"):
                                                                                                                """Accepts a task from the user interface and immediately returns control to user."""
                                                                                                                        task_id = str(uuid.uuid4())
                                                                                                                                
                                                                                                                                        # Log to structural SQLite DB so power failure won't wipe the queue record
                                                                                                                                                self.db.register_task(task_id, description, assigned_model)
                                                                                                                                                        
                                                                                                                                                                task_payload = {
                                                                                                                                                                            "task_id": task_id,
                                                                                                                                                                                        "func": sync_function,
                                                                                                                                                                                                    "args": args,
                                                                                                                                                                                                                "description": description
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        # Drop into processing pipeline
                                                                                                                                                                                                                                                await self.queue.put(task_payload)
                                                                                                                                                                                                                                                        return task_id  # Returns ID immediately so UI doesn't lock up

                                                                                                                                                                                                                                                            async def _execute_worker(self, task_payload):
                                                                                                                                                                                                                                                                    """The actual processor that executes the code and intercepts failures."""
                                                                                                                                                                                                                                                                            task_id = task_payload["task_id"]
                                                                                                                                                                                                                                                                                    func = task_payload["func"]
                                                                                                                                                                                                                                                                                            args = task_payload["args"]
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                            self.db.update_task_status(task_id, "running")
                                                                                                                                                                                                                                                                                                                    loop = asyncio.get_running_loop()
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                # Run the system automation function inside our isolated thread pool
                                                                                                                                                                                                                                                                                                                                                            await loop.run_in_executor(self.thread_executor, func, *args)
                                                                                                                                                                                                                                                                                                                                                                        self.db.update_task_status(task_id, "completed")
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                            except Exception as err:
                                                                                                                                                                                                                                                                                                                                                                                                        # Capture structural system breakdown backtraces safely
                                                                                                                                                                                                                                                                                                                                                                                                                    error_msg = f"{str(err)}\nTraceback:\n{traceback.format_exc()}"
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                            # Write to database for Self-Diagnosis routines later
                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.db.update_task_status(task_id, "failed", error_log=error_msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Send alert to Core for translation to regional languages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"\n[{datetime.now().strftime('%H:%M:%S')}] ALERT: Background task {task_id} failed. Error caught.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            